//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeStaff_Table
    {
        public string OfficeStaff_UserName { get; set; }
        public string Password { get; set; }
    }
}
